version: "2.1"
services:
    homer:
        image: b4bz/homer
        container_name: homer
        environment:
          - UID=1000
          - GID=1000
        volumes:
          - ~/homer/assets:/www/assets
        ports:
          - 80:8080
