---
title: "The Lake House"
subtitle: "App dashboard"
logo: "assets/hassio_small.gif"
header: true

columns: "3"
connectivityCheck: true

theme: default

stylesheet:
  - "assets/custom.css"

colors:
  light:
    highlight-primary: "#aaaaaa"
    highlight-secondary: "#c1c1c1"
    highlight-hover: "#dcdcdc"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
    background-image: "assets/bg.jpg"

  dark:
    highlight-primary: "#0b0b0b"
    highlight-secondary: "#101111"
    highlight-hover: "#313232"
    background: "#1b1c1c"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"
    background-image: "assets/bg.jpg"

footer: "<p><a class=\"footer-link\" href=\"https://github.com/JorgeAnzola/homer-dashboard\"><i class=\"fab fa-github\"></i> Dashboard repository</a></p>"

links:
  - name: "Jorge Anzola"
    icon: "fab fa-github"
    url: "https://github.com/jorgeanzola"
    target: "_blank"

services:
  - name: "Media center"
    logo: "assets/icons/popcorn.png"
    items:
      - name: "Plex"
        logo: "assets/icons/plex.png"
        subtitle: "Media streaming service"
        url: "http://192.168.178.35:32400/web/index.html#!/"
#        type: "Ping"
        target: "_blank"

      - name: "Radarr"
        logo: "assets/icons/radarr.png"
        subtitle: "Movies PVR for BitTorrent"
        url: "http://192.168.178.35:7878"
#        type: "Radarr"
        target: "_blank"
        apiKey: "c66116610b2e4a79ae6e6448933746be"

      - name: "Sonarr"
        logo: "assets/icons/sonarr.png"
        subtitle: "TV shows PVR for BitTorrent"
        url: "http://192.168.178.35:8989/"
#        type: "Sonarr"
        target: "_blank"

      - name: "Jackett"
        logo: "assets/icons/jackett.png"
        subtitle: "API support for torrent trackers"
        url: "http://192.168.178.35:9117/"
#        type: "Ping"
        target: "_blank"

      - name: "Transmission"
        logo: "assets/icons/transmission.png"
        subtitle: "BitTorrent client"
        url: "http://192.168.178.35:9091/"
#        type: "Ping"
        target: "_blank"

      - name: "Configuration repository"
        logo: "assets/icons/github.png"
        url: "https://github.com/JorgeAnzola/media-center"
        target: "_blank"

  - name: "Home Automation"
    logo: "assets/icons/house.png"
    items:
      - name: "Home Assistant - Production"
        logo: "assets/icons/home-assistant.png"
        subtitle: "Home Assistant production instance"
        url: "http://192.168.178.35:8123"
#        type: "Ping"
        target: "_blank"

      - name: "Home Assistant - Development"
        logo: "assets/icons/home-assistant.png"
        subtitle: "Home Assistant development instance"
        url: "http://homeassistant.local:8123/"
#        type: "Ping"
        target: "_blank"

      - name: "InfluxDB (WIP)"
        logo: "assets/icons/influx.png"
        subtitle: "Open-source time series database"
        url: "#"
#        type: "Ping"
        target: "_blank"

      - name: "Configuration repository"
        logo: "assets/icons/github.png"
        url: "https://github.com/JorgeAnzola/home-assistant-config/"
        target: "_blank"

  - name: "Monitoring and tools"
    logo: "assets/icons/heart.png"
    items:
      - name: "Router"
        logo: "assets/icons/router.png"
        subtitle: "Connect Box settings"
        url: "http://192.168.178.1"
#        type: "Ping"
        target: "_blank"

      - name: "Portainer"
        logo: "assets/icons/docker.png"
        subtitle: "Open source container management UI"
        url: "http://192.168.178.35:9000"
#        type: "Ping"
        target: "_blank"

      - name: "Tautulli"
        logo: "assets/icons/tautulli.png"
        subtitle: "Media server activity monitor"
        url: "http://192.168.178.35:8181/"
#        type: "Ping"
        target: "_blank"

      - name: "Kibana (WIP)"
        logo: "assets/icons/elastic.png"
        subtitle: "Log visualization"
        url: "#"
#        type: "Ping"
        target: "_blank"

      - name: "Grafana (WIP)"
        logo: "assets/icons/grafana.png"
        subtitle: "Analytics dashboard"
        url: "#"
#        type: "Ping"
        target: "_blank"
